Workflow lidarprod optim
IGNF/myria3d pull request #117
Opened 2024-04-18 14:53 UTC by leavauchier

2024-04-25 12:16 UTC, CharlesGaydon requested changes
Quelques corrections et typos mais globalement c'est top :)

2024-04-25 12:16 UTC, CharlesGaydon commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +          Il correspond au nom du fichier checkpoint à utiliser pour les prédictions (sans l'extension !)
Je préciserais 
> sans l'extension `gpkg`

2024-04-25 12:16 UTC, CharlesGaydon commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +      OUTPUT_DIR: /var/data/LIDAR-PROD-OPTIMIZATION/${{ github.event.inputs.sampling_name }}/${{ github.event.inputs.model_id }}
nitpick: terminer par un `/` comme pour `LOGS_DIR`

2024-04-25 12:16 UTC, CharlesGaydon commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +      LOGS_DIR: /var/data/MYRIA3D-SHARED-WORKSPACE/${{ github.event.inputs.user }}/${{ github.event.inputs.sampling_name }}/
`LOGS_DIR` contiendra les logs hydra de l'inférence il me semble. Pour moi ces logs ont plus leur place dans OUTPUT_DIR, avec les prédictions. A priori pas un soucis d'avoir des `.laz` et des fichiers de log au même endroit, puisque lorsqu'on liste les fichier dans lidar-prod on filtre sur les extensions laz/las.

2024-04-25 12:16 UTC, CharlesGaydon commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +      BATCH_SIZE: 2
Une plus grosse batch size devrait accélérer l'inférence. Après il faut composer avec les limites de la VM évidemment. Mais je pense que bs=25 ca reste raisonnable (cf. les paramètres de prod, qui sont à 50 je crois)

2024-04-25 12:16 UTC, CharlesGaydon commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +          echo "Run prediction on lidar-prod optimzation datasets (val and test)"
optimzation -> optimization

2024-04-25 12:16 UTC, CharlesGaydon commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +          echo "checkpoint name ${{ github.event.inputs.model_id }}"
niptick: ajouter un `:`

2024-04-25 12:16 UTC, CharlesGaydon commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +          echo "checkpoint name ${{ github.event.inputs.model_id }}"
ici et en pour predict config

2024-04-25 12:16 UTC, CharlesGaydon commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +      LOGS_DIR: /var/data/MYRIA3D-SHARED-WORKSPACE/${{ github.event.inputs.user }}/${{ github.event.inputs.sampling_name }}/
mea culpa, LOGS_DIR ce sont les logs de _l'entraînement_ du modèle en fait, qui est censé contenir la config et le checkpoint c'est ça ?
Dans ce cas je le renommerai explicitement en `CONFIG_DIR,` car là on pense au logs de sortie de l'inférence. Et en soit ckpt et yaml peuvent avoir été déplacés dans un dossier ad-hoc qui n'est plus un `LOGS_DIR`

2024-04-25 12:16 UTC, CharlesGaydon commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +          datamodule.batch_size=${{env.BATCH_SIZE}}
Ici j'ajouterais `datamodule.tile_width=1000` pour éviter un type d'erreur difficile à repérer. 

Si la config a mal été transformée en une configuration de prédiction, elle garde trace du fait que les nuages issus de pacasam faisaient déjà 50 x 50m. Si le param n'est pas modifié, seul 50 x 50 m de la tuiles seront inférés...

2024-04-25 12:16 UTC, CharlesGaydon commented on CHANGELOG.md
> +(in order to automate thresholds optimisation)
ajouter un point
optimisation -> optimization (american english)

2024-04-25 12:34 UTC, leavauchier commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +      BATCH_SIZE: 2
J'ai des problèmes de ram sur certaines dalles assez lourdes, ça ne passe pas avec un batch-size de 5, d'où la valeur plus petite.

2024-05-02 13:54 UTC, leavauchier commented on .github/workflows/predict-for-lidar-prod-optimization.yml
> +      BATCH_SIZE: 2
j'ai remonté à 25 après avoir réglé le problème de RAM

2024-05-06 15:58 UTC, CharlesGaydon approved these changes
👍🏻  !
LGTM :)

2024-05-07 07:43 UTC, merged