add get_las_paths_by_split_dict to utils
IGNF/myria3d pull request #42
Opened 2022-10-14 08:04 UTC by MichelDaab

2022-10-14 09:31 UTC, CharlesGaydon requested changes
Quelques petits commentaires de structure surtout. C'est bien d'avoir ces nouvelles fonctions d'abstraction,  elles rendet le code plus clair :)

2022-10-14 09:31 UTC, CharlesGaydon commented on myria3d/pctl/dataset/utils.py
> +    """Create a HDF5 dataset file from las.
Dosctring à actualiser :)

2022-10-14 09:31 UTC, CharlesGaydon commented on myria3d/pctl/dataset/utils.py
> +def create_hdf5(
Pas bloquant, mais en fait je préférerais laisser cette fonction dans le fichier hdf5.py, pour que tout ce qui est spécifique à ce format s'y retrouve. Et dans utils il y a ce qui est commun à différentes formes de dataset (comme COPC, dont pour l'instant le dataloader n'est pas implémenté, mais que je souhaite garder encore pour tests éventuels plus tard).

2022-10-14 09:31 UTC, CharlesGaydon commented on run.py
> +        """build an HDF5 file from a directory with las files"""
Majuscule + Ponctuation.

2022-10-14 09:31 UTC, CharlesGaydon commented on run.py
> +    HDF5 = "hdf5"
`hdf5` --> `create_hdf5` pour garder la convention de verbe ?

2022-10-21 09:46 UTC, CharlesGaydon commented
Changements de main à intégrer également ; par ailleurs le numéro de version devra être actualisé également (sur main actuel : V3.1.0)

2022-10-24 06:40 UTC, MichelDaab commented on myria3d/pctl/dataset/utils.py
> +def create_hdf5(
si tu préfères

2022-10-24 07:14 UTC, MichelDaab commented on myria3d/pctl/dataset/utils.py
> +    """Create a HDF5 dataset file from las.
ok

2022-10-24 07:19 UTC, MichelDaab commented on run.py
> +    HDF5 = "hdf5"
ok

2022-10-24 07:20 UTC, MichelDaab commented on run.py
> +        """build an HDF5 file from a directory with las files"""
ok

2022-10-24 13:15 UTC, CharlesGaydon reviewed
Merci ! 
Est-ce que tu peux documenter cette nouvelle "task" dans la documentation ?
Je pense qu'à cette [section](https://ignf.github.io/myria3d/tutorials/prepare_dataset.html#using-your-own-data) ce serait adapté, par exemple en modifiant
> This happens on the fly, therefore a first training might take some time, but this should only happens once.
Maintenant c'est soit "on the fly" lorsqu'on fit, soit en précisant un mot clef (rajouter la ligne de commande qui va bien) :)

2022-10-24 13:15 UTC, CharlesGaydon commented on package_metadata.yaml
> +__version__: "3.0.3"
La version actuelle est passée à V3.1.0. Donc la nouvelle peut être V3.1.1.

2022-10-24 14:39 UTC, CharlesGaydon approved these changes
LGTM.

2022-10-24 14:41 UTC, merged