20230116 A Transform to ignore artefact points
IGNF/myria3d pull request #52
Opened 2023-01-16 14:09 UTC by CharlesGaydon

2023-01-16 14:29 UTC, CharlesGaydon commented
@MichelDaab  On mergera d'abord ta PR, pour éviter de nouveaux conflits ;)

2023-01-16 17:00 UTC, CharlesGaydon commented
Artefacts ignorés :
![artefacts_ignorés](https://user-images.githubusercontent.com/11660435/212731648-c014d174-a5e2-4a5c-a2be-bfc5ccec40df.png)
Artefacts gardés :
![artefacts_gardés](https://user-images.githubusercontent.com/11660435/212731699-c5cfb1f7-080e-4b0b-9e37-7905be7924f9.png)
Exemple où l'on est robuste aux artefacts, mais illustrant qu'ils sont bien pris en compte et que les points artefacts ne sont pas prédits (il prennent la valeur de leur voisins)

2023-01-31 09:21 UTC, CharlesGaydon commented
@MichelDaab Prêt pour revue :) Est-ce que tu penses pouvoir la faire lundi ? Il n'y a pas une urgence énorme mais c'est une amélioration utile en prod :)

2023-01-31 09:34 UTC, CharlesGaydon commented
![image](https://user-images.githubusercontent.com/11660435/215722505-8f7f3cd3-c3f4-48b1-9796-e12a8cb95079.png)

Ils sont bien ignorés.

2023-02-06 14:28 UTC, MichelDaab requested changes
Ma principale remarque est que les instantiations par hydra sont super relou à remonter quand on n'est pas à l'origine de l'arborescence et qu'on doit chercher ce que fait une modification.

Autement il y a deux-trois petites choses mineures que j'ai vues passer

2023-02-07 05:41 UTC, CharlesGaydon commented on myria3d/models/interpolation.py
> +        return reduced_logits[idx_in_full_cloud], idx_in_full_cloud
Bien vu !

2023-02-07 05:43 UTC, CharlesGaydon commented on myria3d/models/interpolation.py
> +        del idx_in_full_cloud
Léa Vauchier avait remarqué une empreinte mémoire forte à l'étape d'interpolation, et que l'ajout de quelques délétions réduisait de manière non négligeable cette empreinte - c'est à la marge mais c'est mieux que rien :)

2023-02-07 05:45 UTC, CharlesGaydon commented on .github/workflows/cicd.yaml
> -        --config-path /inputs/
Je crois que j'ai seulement changé l'ordre des tests mais les deux cas (avec et sans override) sont bien présents :) Il me semble que c'était dans une optique que l'exemple "par défaut" n'ait pas l'overlap.

2023-02-07 06:07 UTC, merged